### ISSUE TITLE
Monokakido parser improvements

### ISSUE THREAD

**Issue by Jimmy-Z** [stephenmk/jitenbot#6]
I was pointed here by a forum post by @epistularum: https://forum.freemdict.com/t/topic/22479/13

I heard that you're _not very proficient_ with Rust (no offense), I'd like to help on that front if that's ok.

At first glance, your audio -> media MR used a String to distinguish between audio and graphics, Rustaceans would use an enum since enums are cheap in memory consumption and comparison. And most of the time when working with strings. &str is preferred over String to save memory and copying costs. There might be other things but I didn't look further, 

This kind of thing could be the reason your MR is not accepted, and something that @golddranks is too polite to point out. (no offense, again).

If it's ok, I'd like to re-implement your MR in somewhat better rust, and try to get it merged, I'd like not to maintain a fork if that's possible.

Thanks for your work, and sorry for the rudeness.

**Comment by stephenmk** [comment]
No offense taken. You're correct, I don't have any experience with rust. I just modified the program to add a feature that I and other people needed (extracting image files). For the record, I'll admit that I'm not very proficient with python either. If you have suggestions on how to make jitenbot more pythonic, I'd be excited to hear those as well.

If I may also say something potentially offensive (:stuck_out_tongue_winking_eye:), I don't think rust is a great choice for the functionality that I'm interested in. I simply want to decode the monokakido images, audio, and XML page files into plain-text formats. Memory consumption and performance are not big concerns. Golddranks seems to envision that project as tool for querying the monokakido data and retrieving definitions, and [gallons of ink have been spilled](https://old.reddit.com/r/rust/comments/10u4anm/how_to_use_mmap_safely_in_rust/) over how to do this efficiently. I think this is a problem for the user's favorite dictionary client (goldendict, etc.) to handle, and I don't want to spend time reinventing that wheel.

So while I appreciate the work Golddranks has done, our goals are not completely aligned. Rather than investing time into that project, I would rather like to see if the specific functionality that I need could be reimplemented into a concise python module. That would make it easier to integrate with jitenbot so that users would not need [to jump through so many hoops](https://github.com/stephenmk/jitenbot#monokakido-targets) to import the monokakido data. I haven't yet spent any time on this because so far I've been able to get all the data I need from Golddrank's tool (albeit with [some trouble](https://github.com/golddranks/monokakido/issues/5)).

So anyway, yes, absolutely feel free to modify my MR. If you're just looking for ways to contribute to jitenbot, let me know and I can put together some more specific notes. Jitenbot doesn't have much documentation and I'm not confident that the code will make any sense just by reading it, so I can try to write up an overview if you'd like.

**Comment by Jimmy-Z** [comment]
[I also asked @golddranks and he replied](https://github.com/golddranks/monokakido/pull/4), so it turns out my rudeness was entirely unnecessary.

> I don't think rust is a great choice for the functionality that I'm interested in.

I agree with you, python would be a more practical choice for your goal.

But on the other hand, rust is better for his.

> So while I appreciate the work Golddranks has done, our goals are not completely aligned.

I have to say I'm more interested in his goal: support monokakido format natively instead of converting it to another format.

One of the reasons is that I don't really like the mdx format in particular, it's not even an open format in the beginning, it's reverse engineered. 

In the long run, since it's an open source library everyone could use, dict apps like goldendict _could_ simply link it to gain the functionality to read monokakido directly instead of reading converted mdx files.

That said, our goals do have some common interests.

> users would not need [to jump through so many hoops](https://github.com/stephenmk/jitenbot#monokakido-targets) to import the monokakido data.

I might be wrong, but from what I've seen, it's just two commands vs one command, and jitenbot is a command line tool so not really end user friendly anyway, that's just my opinion though.

I can't really say I'm better at python than you're since I haven't read it yet, let alone provide suggestions.

Thanks for offering to provide notes, but I guess it would be more efficient for me to have a glimpse over the code (of the two projects) over the weekend, then I can probably ask some specific questions.

Thanks.

**Comment by Jimmy-Z** [comment]
the file header magic check https://github.com/stephenmk/monokakido/blob/3a0e0d2ea7779de4c2c549bce6e0eb3d3219e4f0/src/key.rs#L36 fails for me on SANKOKU8 since magic3 is not 0, this is strange since you had it supported and I did not see you removing this check. did you forget to push this change? or you simply had a different set of files?

[I also asked @golddranks.](https://github.com/golddranks/monokakido/pull/4#issuecomment-1675842734)

**Comment by stephenmk** [comment]
Indeed, this is a problem we had to work around because the current version of the library fails the check. Since jitenbot does not use the index files produced by the parser library, [we avoided the problem](https://github.com/stephenmk/monokakido/commit/3a0e0d2ea7779de4c2c549bce6e0eb3d3219e4f0#commitcomment-122083405) by replacing the sankoku8 index files with the files from a dictionary which did not cause the library to crash. We only need to decode the XML page files for sankoku8, so this was enough to get what we wanted.

This is one of the "hoops" that we have to jump through that I mentioned before. Of course, there's no reason why the parser needs to be reimplemented in python in order to solve the problem. It would no doubt be easier to write some wrapper code to interface with the rust executable if it becomes stable and flexible enough. So any improvements that you make to the rust library will be very useful and very much appreciated.

**Comment by Jimmy-Z** [comment]
Thanks for the explanation and sorry for missing that 🙈 

I just lost interest in my previous immediate goal NHKACCENT2 since I just found out SMK8 has audio.

My current plan would be (in no particular order):
* some automatic tests, make a compatibility list.
* when exploding, skip errors instead of panicking and explode what we can, which should save some trouble for cases like SANKOKU8.
* issues I listed in [that post](https://github.com/golddranks/monokakido/pull/4#issuecomment-1675842734).

I'd like to hear your opinions too 🙉

**Comment by stephenmk** [comment]
> Thanks for the explanation and sorry for missing that

No worries. All of this information is a little disorganized, so details like that are easy to miss.

> I'd like to hear your opinions too

I think your plan sounds great. All of the issues you've identified would be worthwhile to solve. If the parser library stops panicking so much and is able to accept a base path from the user, then the library will be much easier to integrate with my jitenbot application.

**Comment by Jimmy-Z** [comment]
Hi, I think I've done writing a (slightly) better exploding tool:

https://github.com/Jimmy-Z/mkd-utils

Please do tell me your thoughts about it 🙉

**Comment by stephenmk** [comment]
This looks very cool. Thank you for putting this together.

I wondered why you split this functionality into a new project rather than adding it to the original monokakido tool. My guess is that the new project introduces new dependencies, and you did not want to add these new dependencies to the original tool. I think it's fine either way, but other people may ask the same question.

Unfortunately I don't have any suggestions on how to improve the tool, because it seems like it already does everything I need. I was going to suggest that the tool should also explode the keystore archives, but now I see that this is already on your TODO list. There are also still the `InvalidIndex` errors that we still have to solve for dictionaries like daijirin2. Other than that, it seems perfect to me.

**Comment by Jimmy-Z** [comment]
I put it in a new repo because it's drastically different from the original explode, I'm not sure if it will be a welcomed change. 

golddranks will always be welcome to absorb that back into his project if he deems it's worthful.

To be more specific, it doesn't use higher-level APIs like `MonokakidoDict` or `Audio`/`Media`, it instead calls lower-level APIs like `resource::{Rsc, Nrsc}`, the upper-level code is rewritten to be more forgivable, verbose and versatile (shameless bragging).

`.keystore` exploding is not done yet because of two reasons:
* when I asked about the SANKOKU8 issue, you informed me that the index files (converted from the headword.keystore file, I believe) were not used by jitenbot, so it took a lower priority.
    * please correct me if I'm wrong.
    * or please tell me what role it plays, I'm still not familiar with the whole dictionary data structure.
        * like why jitenbot could simply not use it, does jitenbot extracts headwords from pages on its own?
* I fixed two key header parsing issues:
https://github.com/golddranks/monokakido/commit/971ed05b58e044eff0b2b0311656c7ff547d45fa
https://github.com/golddranks/monokakido/commit/c6e44e907810db2f1cf2d74ff71b2f5f996d036c
while fixing those, I spotted several potential bugs in the key parsing code, but I'm not quite sure yet, until then, writing keystore exploding is pointless.

I did see some `InvalidIndex` error while exploding contents rsc , but not on DAIJIRIN2, could you share the output of `cargo run --release -- scan-dict DAIJIRIN2` with me? mine for comparison:
```
大辞林 第四版 | DAIJIRIN 4 [DAIJIRIN2(1.0.1)]
        大辞林 [SANSEIDO-DAIJIRIN2(1)]
                contents: contents.idx
                contents: contents.map
                contents: rsc: 22
                        initialized rsc(map|idx)
                        182633 entries
                        success: 182633
                entries: entries: 394
                gaiji: svg: 89
                graphics: index.nidx
                graphics: nrsc: 3
                        initialized nrsc(nidx)
                        2744 entries
                        success: 2744
                headline: headlinestore: 2
                index: plist: 54
                key: idiom.keystore
                key: kanji.keystore
                key: example.keystore
                key: headword.keystore
                key: stringstore: 1
                        initialized keystore from idiom.keystore
                        initialized keystore from kanji.keystore
                        initialized keystore from example.keystore
                        initialized keystore from headword.keystore
                migration: migration: 1
                misc: not file: 2

```
(use the latest commit I just pushed)

And there's also `ZlibError` with some audio rsc, this could simply be Monokakido finally figured that there's no point compressing AAC with Zlib.

If jitenbot indeed can extract headwords from pages, I think I'll continue focusing on these rsc issues.

**Comment by stephenmk** [comment]
> when I asked about the SANKOKU8 issue, you informed me that the index files (converted from the headword.keystore file, I believe) were not used by jitenbot, so it took a lower priority. 

Correct

> or please tell me what role it plays, I'm still not familiar with the whole dictionary data structure. like why jitenbot could simply not use it, does jitenbot extracts headwords from pages on its own?

Yes, jitenbot extracts the headwords from the pages. There are a few problems* that make the headwords from the index files difficult to work with, so it is easier to get the headwords from the pages. I included more details at the end of this post, but it's not very important.

However, there may still be useful information that can be extracted from the index files that we cannot extract from the page. For example, the headword markup in the page for ままならぬ in NHKACCENT2 looks like this:

```xml
<h>
  <headword>ままならぬ</headword>
  <d_angle_brackets class="h">《×儘》</d_angle_brackets>
</h>
```

There is not enough information in this page to determine that the kanji form of this entry is supposed to be 儘ならぬ. We may be able to retrieve this information from the index file, however. So that is why it would be useful to decode those files.

> I did see some InvalidIndex error while exploding contents rsc , but not on DAIJIRIN2

Yes, I do not see any errors when using `mkd-utils` on DAIJIRIN2. Only the original monokakido tool still produces an error. If the problem has already been solved by `mkd-utils`, that's great news.

> If jitenbot indeed can extract headwords from pages, I think I'll continue focusing on these rsc issues.

I agree that the rsc issues are probably more important. Whatever you choose to work on, your help is greatly appreciated.

---

<details>
<summary>*Problems with headwords from index files</summary>

1. For the monokakido dictionaries, **all** of the headwords have been converted to use katakana instead of hiragana. So in order to use these keys, we would need to figure out how to convert the keys that should use hiragana back to hiragana. This is difficult because we need some way to know that あんちょこ should be written in hiragana and アンチョビ should be written in katakana. Otherwise, if we do not convert the keys back to their standard forms, then the search keys will not be useful. GoldenDict will not find the entry for コーヒー if you search for こーひー, for example.

2. The monokakido headword index files do not associate kana forms with kanji forms. For example, a single entry might contain four search keys: `案`, `案ジル`, `アン`, and `アンジル`. Without some clever heuristics, there is no way of knowing that `あん` is the reading of `案` and `あんじる` is the reading of `案じる`. In order to disambiguate terms during term lookups, jitenbot produces search keys with both the reading and kanji form such as `あん【案】`. We wouldn't want to accidentally produce an incorrect key such as `あんじる【案】`.

3. The index files contain many source-language headwords that I do not want to use. For example, "chocolate" might be included as a keyword for "チョコレート". This might be a controversial decision and many people might like to be able to search for the original English source words, but I currently have some very particular and technical reasons for wanting to format the headwords this way.

</details>

**Comment by Jimmy-Z** [comment]
>> I did see some InvalidIndex error while exploding contents rsc , but not on DAIJIRIN2
>
> Yes, I do not see any errors when using mkd-utils on DAIJIRIN2. Only the original monokakido tool still produces an error. If the problem has already been solved by mkd-utils, that's great news.

Well, I thought that was strange since that's a lower level error, I did basically nothing on those, so I tested the original explode, turns out this error happens in keystore exploding, mkd-utils just skipped that part, I'd guess it's caused by the potential key parsing bugs I noticed.

**Comment by Jimmy-Z** [comment]
I've fixed (not pushed yet) the key parsing issues I mentioned before, but that doesn't improve much since there're deeper issues, like:
* https://github.com/golddranks/monokakido/blob/5ec9bd59ecd3836ac6fa81becd4401453f238310/src/key.rs#L215
* https://github.com/golddranks/monokakido/blob/5ec9bd59ecd3836ac6fa81becd4401453f238310/src/key.rs#L299

Unfortunately, while my rust skills are ok, my reverse engineering skills are not, I'll still work on this, but don't count on me 😞

**Comment by stephenmk** [comment]
I have added `mkd-utils` [as a dependency within Jitenbot](https://github.com/stephenmk/jitenbot/blob/eb479d767ce4a110343ab04e74c3a6bf9ea1bb96/bot/crawlers/base/mkd.py#L44-L48) so that the program may now automatically fetch [all the media](https://github.com/stephenmk/jitenbot/blob/eb479d767ce4a110343ab04e74c3a6bf9ea1bb96/bot/crawlers/smk8.py#L9-L14) and [page data](https://github.com/stephenmk/jitenbot/blob/eb479d767ce4a110343ab04e74c3a6bf9ea1bb96/bot/crawlers/base/mkd.py#L18-L21) that it needs. Thanks again for all the great work.
